services:
  template-microsoft-foundry:
    container_name: template-microsoft-foundry
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "http.server", "8000"]
    env_file:
      - .env
    environment:
      PROJECT_NAME: hello
    ports:
      - "8000:8000"
